services:
  # Main Web Application (Development)
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_MOCK_APIS=true
      - DEVELOPMENT_PHASE=1
      # Supabase Cloud Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      # AI Integration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFLOW_URL=http://langflow:7860
      # Caching
      - REDIS_URL=redis://redis:6379
    depends_on:
      - langflow
      - redis
    volumes:
      - ./packages/web:/app/packages/web
      - /app/packages/web/node_modules
    restart: unless-stopped
    command: npm run dev

  # Langflow (AI Workflows) - Using Supabase Cloud
  langflow:
    image: langflowai/langflow:latest
    environment:
      - LANGFLOW_DATABASE_URL=${SUPABASE_URL}
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=admin
      - LANGFLOW_SECRET_KEY=your-secret-key-here
    ports:
      - "7860:7860"
    volumes:
      - ./packages/langflow/flows:/app/flows
      - ./packages/langflow/data:/app/data
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: 