services:
  # Main Web Application (Development)
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_MOCK_APIS=true
      - DEVELOPMENT_PHASE=1
      # Supabase Cloud Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      # AI Integration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGGRAPH_URL=http://langgraph:8000
      - ENABLE_LANGGRAPH=true
      # Caching
      - REDIS_URL=redis://redis:6379
    depends_on:
      - langgraph
      - redis
    volumes:
      - ./packages/web:/app/packages/web
      - /app/packages/web/node_modules
    restart: unless-stopped
    command: npm run dev

  # LangGraph (AI Workflows)
  langgraph:
    build:
      context: packages/langgraph
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: 