version: '3.8'

services:
  # Main Web Application (Production)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USE_MOCK_APIS=${USE_MOCK_APIS:-false}
      
      # Supabase Cloud Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # AI Integration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGGRAPH_URL=http://langgraph:8000
      - ENABLE_LANGGRAPH=true
      
      # Travel APIs
      - TEQUILA_API_KEY=${TEQUILA_API_KEY}
      - BOOKING_API_KEY=${BOOKING_API_KEY}
      - VIATOR_API_KEY=${VIATOR_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
      
      # Advanced APIs
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ROME2RIO_API_KEY=${ROME2RIO_API_KEY}
      - FLIGHTAWARE_API_KEY=${FLIGHTAWARE_API_KEY}
      - FOURSQUARE_API_KEY=${FOURSQUARE_API_KEY}
      
      # Payments
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      
      # Infrastructure
      - REDIS_URL=redis://redis:6379
      
      # Browser Automation
      - BROWSER_USE_HEADLESS=true
      - AUTOMATION_USER_AGENT=TravelAgentic/1.0
      
    depends_on:
      - langgraph
      - redis
    restart: unless-stopped
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  # LangGraph (AI Workflows)
  langgraph:
    build:
      context: packages/langgraph
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBSERVER_URL=http://web:3000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Redis (Caching & Sessions)
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Nginx (Load Balancer & SSL Termination)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis-data:

networks:
  default:
    driver: bridge 